'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucRefund
    
    '''<summary>
    '''txtRCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRCustomerName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRProspectNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRProspectNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRCondition As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRNamaSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRNamaSupplier As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRDAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDAdmin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRDAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRDBunga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDBunga As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRDProvisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDProvisi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRDTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRDTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRHAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRHAdmin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRHAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRHAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRHBunga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRHBunga As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRHProvisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRHProvisi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRHTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRHTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRowCount As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
