'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucSurvey
    
    '''<summary>
    '''txtCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProspectNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProspectNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurveyI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurveyI As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurveyII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurveyII As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamatSurveyDebitur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamatSurveyDebitur As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamatSurveyDebiturNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamatSurveyDebiturNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamatSurveyUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamatSurveyUnit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamatSurveyUnitNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamatSurveyUnitNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlamatUsaha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamatUsaha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTujuanSurveyPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTujuanSurveyPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTujuanSurveyKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTujuanSurveyKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStatusPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStatusKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurveyorPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurveyorPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurveyorKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurveyorKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAssignDatePertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignDatePertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAssignDateKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignDateKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDownloadPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDownloadPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDownloadKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDownloadKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReadPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReadPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReadKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReadKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStartDatePertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDatePertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStartDateKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDateKedua As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSubmitDatePertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubmitDatePertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSubmitDateKedua control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubmitDateKedua As Global.System.Web.UI.WebControls.TextBox
End Class
