'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BM_StartPage
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''frmMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''userid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''branchid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents branchid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnredirect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnredirect As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''sm1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''up control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''currentTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currentTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Dynamic_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dynamic_Panel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''refreshTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents refreshTimer As Global.System.Web.UI.Timer
    
    '''<summary>
    '''txtCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hdnstatusid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstatusid As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBranchId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserID As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccess As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdataid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdataid As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''hdnsortby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnsortby As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''hdnsortmethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnsortmethod As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
