'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CalculatorCreditHistory
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtCBranchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBranchName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCustName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCAssetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCAssetName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCShowroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCShowroom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBatasAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBatasAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPenutupanAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPenutupanAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCCoverAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCoverAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCDepresiasiAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDepresiasiAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPerluasanSRCCTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPerluasanSRCCTS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPerluasaanGempaBumi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPerluasaanGempaBumi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPerluasanBanjir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPerluasanBanjir As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTHJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTHJ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPerusahaanAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPerusahaanAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCCabangWilayahAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCabangWilayahAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCKategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCKategori As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPenggunaanOkupasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPenggunaanOkupasi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTypeAngsuran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTypeAngsuran As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBuanaProtectionKapitalis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBuanaProtectionKapitalis As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTenorPembiayaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTenorPembiayaan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTahunKendaraan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTahunKendaraan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCDpPersen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDpPersen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCDpAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDpAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCOtrAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOtrAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBiayaAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBiayaAdmin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCFiducia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCFiducia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBiayaPolisAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBiayaPolisAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBiayaProvisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBiayaProvisi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBiayaBuanaProtection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBiayaBuanaProtection As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCOtrAmount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOtrAmount2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCDpAmount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDpAmount2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPhMurni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPhMurni As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCKapitalisasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCKapitalisasi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTotalPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTotalPH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBunga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBunga As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPhBunga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPhBunga As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCltv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCltv As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPremiAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPremiAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCThjDibayarDimuka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCThjDibayarDimuka As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTotalPremiAsuransi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTotalPremiAsuransi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPolisAsuransiDibayarDimuka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPolisAsuransiDibayarDimuka As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCAdministrasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCAdministrasi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCFiduciaDibayarDimuka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCFiduciaDibayarDimuka As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCBuanaProtetion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBuanaProtetion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCJualFlat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCJualFlat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCJualEff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCJualEff As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCAngsuranPerBulan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCAngsuranPerBulan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCTotalBayarPertama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTotalBayarPertama As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCPelunasanKeDealer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPelunasanKeDealer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCDeviasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDeviasi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCDeviasiNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDeviasiNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCreateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreateDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMode As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
