'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Host_ScorelistRO
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblactivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblactivity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''userid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''branchid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents branchid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdtabdisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdtabdisplay As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''finaldecision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents finaldecision As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ektp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ektp1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ektp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ektp2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dupcheck1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dupcheck1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''negconfins1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents negconfins1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''negconfins2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents negconfins2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''appi1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents appi1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''appi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents appi2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slik1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slik1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slik2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slik2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''negrec1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents negrec1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''negrec2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents negrec2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''phoneverasliri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phoneverasliri As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pefindo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pefindo1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pefindo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pefindo2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''telco1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents telco1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''telco2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents telco2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CBASPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBASPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PhoneExtra1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneExtra1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PhoneExtra2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneExtra2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''viewcekduplikat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewcekduplikat As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''changestatusbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changestatusbox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnCStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCStat As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''txtUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCabang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCabang As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDataId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcekreffnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcekreffnumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtceknationalid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtceknationalid As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcekname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcekname As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcekbirthdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcekbirthdate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcektempatlahirdebitur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcektempatlahirdebitur As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcekmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcekmobile As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcekvaruserid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcekvaruserid As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Label19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NegativeRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NegativeRecords As Global.System.Web.UI.WebControls.Label
End Class
